// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AppInfo() {
  return window['go']['main']['App']['AppInfo']();
}

export function ChatOnce(arg1) {
  return window['go']['main']['App']['ChatOnce'](arg1);
}

export function ClearChat() {
  return window['go']['main']['App']['ClearChat']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function ListDir(arg1) {
  return window['go']['main']['App']['ListDir'](arg1);
}

export function ListProjects() {
  return window['go']['main']['App']['ListProjects']();
}

export function OpenProject(arg1) {
  return window['go']['main']['App']['OpenProject'](arg1);
}

export function PickProjectDir() {
  return window['go']['main']['App']['PickProjectDir']();
}

export function ReadFile(arg1) {
  return window['go']['main']['App']['ReadFile'](arg1);
}

export function RunAgent(arg1) {
  return window['go']['main']['App']['RunAgent'](arg1);
}

export function RunShell(arg1) {
  return window['go']['main']['App']['RunShell'](arg1);
}

export function SSHKeygen(arg1) {
  return window['go']['main']['App']['SSHKeygen'](arg1);
}

export function SSHListKeys() {
  return window['go']['main']['App']['SSHListKeys']();
}

export function SaveDeepSeekKey(arg1) {
  return window['go']['main']['App']['SaveDeepSeekKey'](arg1);
}

export function SaveDeepSeekModel(arg1) {
  return window['go']['main']['App']['SaveDeepSeekModel'](arg1);
}

export function SaveGitAuth(arg1, arg2) {
  return window['go']['main']['App']['SaveGitAuth'](arg1, arg2);
}

export function SaveShowTerminal(arg1) {
  return window['go']['main']['App']['SaveShowTerminal'](arg1);
}

export function StartTerminal() {
  return window['go']['main']['App']['StartTerminal']();
}

export function StopAgent() {
  return window['go']['main']['App']['StopAgent']();
}

export function StopTerminal() {
  return window['go']['main']['App']['StopTerminal']();
}

export function TerminalWrite(arg1) {
  return window['go']['main']['App']['TerminalWrite'](arg1);
}

export function WriteFile(arg1, arg2) {
  return window['go']['main']['App']['WriteFile'](arg1, arg2);
}
