// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AckWelcome() {
  return window['go']['main']['App']['AckWelcome']();
}

export function ActiveRuns() {
  return window['go']['main']['App']['ActiveRuns']();
}

export function AllowToolForSession(arg1, arg2) {
  return window['go']['main']['App']['AllowToolForSession'](arg1, arg2);
}

export function AppDataDir() {
  return window['go']['main']['App']['AppDataDir']();
}

export function AppInfo() {
  return window['go']['main']['App']['AppInfo']();
}

export function ArchiveChatSession(arg1, arg2) {
  return window['go']['main']['App']['ArchiveChatSession'](arg1, arg2);
}

export function ChatOnce(arg1) {
  return window['go']['main']['App']['ChatOnce'](arg1);
}

export function CheckUpdate() {
  return window['go']['main']['App']['CheckUpdate']();
}

export function ClearAllProviderKeys() {
  return window['go']['main']['App']['ClearAllProviderKeys']();
}

export function ClearChat() {
  return window['go']['main']['App']['ClearChat']();
}

export function ClearDeepSeekKey() {
  return window['go']['main']['App']['ClearDeepSeekKey']();
}

export function ClearLocalKey() {
  return window['go']['main']['App']['ClearLocalKey']();
}

export function ClearOpenRouterKey() {
  return window['go']['main']['App']['ClearOpenRouterKey']();
}

export function ClearQwenKey() {
  return window['go']['main']['App']['ClearQwenKey']();
}

export function ClearTodos(arg1) {
  return window['go']['main']['App']['ClearTodos'](arg1);
}

export function ClearZaiKey() {
  return window['go']['main']['App']['ClearZaiKey']();
}

export function CloneRepo(arg1, arg2) {
  return window['go']['main']['App']['CloneRepo'](arg1, arg2);
}

export function CloneTargetPath(arg1, arg2) {
  return window['go']['main']['App']['CloneTargetPath'](arg1, arg2);
}

export function CloseProject(arg1, arg2) {
  return window['go']['main']['App']['CloseProject'](arg1, arg2);
}

export function CreateProject(arg1, arg2) {
  return window['go']['main']['App']['CreateProject'](arg1, arg2);
}

export function DefaultProjectParentDir() {
  return window['go']['main']['App']['DefaultProjectParentDir']();
}

export function DeleteChatSession(arg1) {
  return window['go']['main']['App']['DeleteChatSession'](arg1);
}

export function DetectDefaultShell() {
  return window['go']['main']['App']['DetectDefaultShell']();
}

export function DuplicateLocalEndpoint(arg1) {
  return window['go']['main']['App']['DuplicateLocalEndpoint'](arg1);
}

export function GetCursorRules() {
  return window['go']['main']['App']['GetCursorRules']();
}

export function GetDeepSeekPeakInfo(arg1) {
  return window['go']['main']['App']['GetDeepSeekPeakInfo'](arg1);
}

export function GetEndSound() {
  return window['go']['main']['App']['GetEndSound']();
}

export function GetOpenRouterBalance() {
  return window['go']['main']['App']['GetOpenRouterBalance']();
}

export function GetProviderNews(arg1) {
  return window['go']['main']['App']['GetProviderNews'](arg1);
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetUsageStats() {
  return window['go']['main']['App']['GetUsageStats']();
}

export function GetWelcome(arg1) {
  return window['go']['main']['App']['GetWelcome'](arg1);
}

export function GetZaiBalance() {
  return window['go']['main']['App']['GetZaiBalance']();
}

export function InstallUpdate() {
  return window['go']['main']['App']['InstallUpdate']();
}

export function ListArchivedChats() {
  return window['go']['main']['App']['ListArchivedChats']();
}

export function ListChatSessions() {
  return window['go']['main']['App']['ListChatSessions']();
}

export function ListDeepSeekModels() {
  return window['go']['main']['App']['ListDeepSeekModels']();
}

export function ListDir(arg1) {
  return window['go']['main']['App']['ListDir'](arg1);
}

export function ListLocalModels() {
  return window['go']['main']['App']['ListLocalModels']();
}

export function ListLocalModelsFor(arg1) {
  return window['go']['main']['App']['ListLocalModelsFor'](arg1);
}

export function ListModelPrices() {
  return window['go']['main']['App']['ListModelPrices']();
}

export function ListOpenRouterModels() {
  return window['go']['main']['App']['ListOpenRouterModels']();
}

export function ListProjects() {
  return window['go']['main']['App']['ListProjects']();
}

export function ListQwenModels() {
  return window['go']['main']['App']['ListQwenModels']();
}

export function ListZaiModels() {
  return window['go']['main']['App']['ListZaiModels']();
}

export function LoadChat(arg1) {
  return window['go']['main']['App']['LoadChat'](arg1);
}

export function LocalBuildHash() {
  return window['go']['main']['App']['LocalBuildHash']();
}

export function MarkProviderNewsRead() {
  return window['go']['main']['App']['MarkProviderNewsRead']();
}

export function NewChatSession(arg1) {
  return window['go']['main']['App']['NewChatSession'](arg1);
}

export function OpenProject(arg1) {
  return window['go']['main']['App']['OpenProject'](arg1);
}

export function PickProjectDir() {
  return window['go']['main']['App']['PickProjectDir']();
}

export function PickProjectParentDir() {
  return window['go']['main']['App']['PickProjectParentDir']();
}

export function PreferDeepSeekModel(arg1) {
  return window['go']['main']['App']['PreferDeepSeekModel'](arg1);
}

export function PreferLocalModel(arg1) {
  return window['go']['main']['App']['PreferLocalModel'](arg1);
}

export function PreferOpenRouterModel(arg1) {
  return window['go']['main']['App']['PreferOpenRouterModel'](arg1);
}

export function PreferQwenModel(arg1) {
  return window['go']['main']['App']['PreferQwenModel'](arg1);
}

export function PreferZaiModel(arg1) {
  return window['go']['main']['App']['PreferZaiModel'](arg1);
}

export function ProbeLocalHealth() {
  return window['go']['main']['App']['ProbeLocalHealth']();
}

export function ProjectHasChats(arg1) {
  return window['go']['main']['App']['ProjectHasChats'](arg1);
}

export function ReadCursorRule(arg1) {
  return window['go']['main']['App']['ReadCursorRule'](arg1);
}

export function ReadFile(arg1) {
  return window['go']['main']['App']['ReadFile'](arg1);
}

export function RefreshProviderPrices() {
  return window['go']['main']['App']['RefreshProviderPrices']();
}

export function ReloadCursorRules() {
  return window['go']['main']['App']['ReloadCursorRules']();
}

export function RemoveLocalEndpoint(arg1) {
  return window['go']['main']['App']['RemoveLocalEndpoint'](arg1);
}

export function RemoveTodos(arg1) {
  return window['go']['main']['App']['RemoveTodos'](arg1);
}

export function RenameChatSession(arg1, arg2) {
  return window['go']['main']['App']['RenameChatSession'](arg1, arg2);
}

export function ResetNetworkStats() {
  return window['go']['main']['App']['ResetNetworkStats']();
}

export function ResolveToolApproval(arg1, arg2, arg3) {
  return window['go']['main']['App']['ResolveToolApproval'](arg1, arg2, arg3);
}

export function ResolveUserAsk(arg1, arg2, arg3) {
  return window['go']['main']['App']['ResolveUserAsk'](arg1, arg2, arg3);
}

export function RunAgent(arg1) {
  return window['go']['main']['App']['RunAgent'](arg1);
}

export function RunAgentWithAttachments(arg1, arg2) {
  return window['go']['main']['App']['RunAgentWithAttachments'](arg1, arg2);
}

export function RunShell(arg1) {
  return window['go']['main']['App']['RunShell'](arg1);
}

export function SSHKeygen(arg1) {
  return window['go']['main']['App']['SSHKeygen'](arg1);
}

export function SSHListKeys() {
  return window['go']['main']['App']['SSHListKeys']();
}

export function SaveActiveProvider(arg1) {
  return window['go']['main']['App']['SaveActiveProvider'](arg1);
}

export function SaveAgentMaxSteps(arg1) {
  return window['go']['main']['App']['SaveAgentMaxSteps'](arg1);
}

export function SaveAgentRetryBudgetSec(arg1) {
  return window['go']['main']['App']['SaveAgentRetryBudgetSec'](arg1);
}

export function SaveAgentRetryCount(arg1) {
  return window['go']['main']['App']['SaveAgentRetryCount'](arg1);
}

export function SaveAgentStallMin(arg1) {
  return window['go']['main']['App']['SaveAgentStallMin'](arg1);
}

export function SaveAgentWarnSteps(arg1) {
  return window['go']['main']['App']['SaveAgentWarnSteps'](arg1);
}

export function SaveAutoModels(arg1) {
  return window['go']['main']['App']['SaveAutoModels'](arg1);
}

export function SaveChat(arg1) {
  return window['go']['main']['App']['SaveChat'](arg1);
}

export function SaveChatSession(arg1, arg2) {
  return window['go']['main']['App']['SaveChatSession'](arg1, arg2);
}

export function SaveComposerHeight(arg1) {
  return window['go']['main']['App']['SaveComposerHeight'](arg1);
}

export function SaveDeepSeekKey(arg1) {
  return window['go']['main']['App']['SaveDeepSeekKey'](arg1);
}

export function SaveDeepSeekModel(arg1) {
  return window['go']['main']['App']['SaveDeepSeekModel'](arg1);
}

export function SaveEndSound(arg1) {
  return window['go']['main']['App']['SaveEndSound'](arg1);
}

export function SaveGitAuth(arg1, arg2) {
  return window['go']['main']['App']['SaveGitAuth'](arg1, arg2);
}

export function SaveHTTP2PingSec(arg1) {
  return window['go']['main']['App']['SaveHTTP2PingSec'](arg1);
}

export function SaveHTTPProtocol(arg1) {
  return window['go']['main']['App']['SaveHTTPProtocol'](arg1);
}

export function SaveLayoutSizes(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['SaveLayoutSizes'](arg1, arg2, arg3, arg4, arg5);
}

export function SaveLocalBaseURL(arg1) {
  return window['go']['main']['App']['SaveLocalBaseURL'](arg1);
}

export function SaveLocalKey(arg1) {
  return window['go']['main']['App']['SaveLocalKey'](arg1);
}

export function SaveLocalLite(arg1) {
  return window['go']['main']['App']['SaveLocalLite'](arg1);
}

export function SaveLocalModel(arg1) {
  return window['go']['main']['App']['SaveLocalModel'](arg1);
}

export function SaveLocalSkipRules(arg1) {
  return window['go']['main']['App']['SaveLocalSkipRules'](arg1);
}

export function SaveMonoFont(arg1) {
  return window['go']['main']['App']['SaveMonoFont'](arg1);
}

export function SaveOpenRouterKey(arg1) {
  return window['go']['main']['App']['SaveOpenRouterKey'](arg1);
}

export function SaveOpenRouterModel(arg1) {
  return window['go']['main']['App']['SaveOpenRouterModel'](arg1);
}

export function SavePlanMode(arg1) {
  return window['go']['main']['App']['SavePlanMode'](arg1);
}

export function SaveQwenEndpoint(arg1) {
  return window['go']['main']['App']['SaveQwenEndpoint'](arg1);
}

export function SaveQwenKey(arg1) {
  return window['go']['main']['App']['SaveQwenKey'](arg1);
}

export function SaveQwenModel(arg1) {
  return window['go']['main']['App']['SaveQwenModel'](arg1);
}

export function SaveShell(arg1) {
  return window['go']['main']['App']['SaveShell'](arg1);
}

export function SaveShowFiles(arg1) {
  return window['go']['main']['App']['SaveShowFiles'](arg1);
}

export function SaveShowSettings(arg1) {
  return window['go']['main']['App']['SaveShowSettings'](arg1);
}

export function SaveShowTerminal(arg1) {
  return window['go']['main']['App']['SaveShowTerminal'](arg1);
}

export function SaveTheme(arg1) {
  return window['go']['main']['App']['SaveTheme'](arg1);
}

export function SaveToolConfirm(arg1) {
  return window['go']['main']['App']['SaveToolConfirm'](arg1);
}

export function SaveUiFont(arg1) {
  return window['go']['main']['App']['SaveUiFont'](arg1);
}

export function SaveWindowGeometry() {
  return window['go']['main']['App']['SaveWindowGeometry']();
}

export function SaveZaiEndpoint(arg1) {
  return window['go']['main']['App']['SaveZaiEndpoint'](arg1);
}

export function SaveZaiKey(arg1) {
  return window['go']['main']['App']['SaveZaiKey'](arg1);
}

export function SaveZaiModel(arg1) {
  return window['go']['main']['App']['SaveZaiModel'](arg1);
}

export function SetIDEContext(arg1, arg2) {
  return window['go']['main']['App']['SetIDEContext'](arg1, arg2);
}

export function StartTerminal() {
  return window['go']['main']['App']['StartTerminal']();
}

export function StartupNotice() {
  return window['go']['main']['App']['StartupNotice']();
}

export function StopAgent() {
  return window['go']['main']['App']['StopAgent']();
}

export function StopAgentSession(arg1) {
  return window['go']['main']['App']['StopAgentSession'](arg1);
}

export function StopTerminal() {
  return window['go']['main']['App']['StopTerminal']();
}

export function SwitchChatSession(arg1) {
  return window['go']['main']['App']['SwitchChatSession'](arg1);
}

export function TerminalResize(arg1, arg2) {
  return window['go']['main']['App']['TerminalResize'](arg1, arg2);
}

export function TerminalWrite(arg1) {
  return window['go']['main']['App']['TerminalWrite'](arg1);
}

export function UpsertLocalEndpoint(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['main']['App']['UpsertLocalEndpoint'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function WriteCursorRule(arg1, arg2) {
  return window['go']['main']['App']['WriteCursorRule'](arg1, arg2);
}

export function WriteFile(arg1, arg2) {
  return window['go']['main']['App']['WriteFile'](arg1, arg2);
}
