// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {chatstore} from '../models';
import {workspace} from '../models';
import {agent} from '../models';

export function AppInfo():Promise<Record<string, string>>;

export function ChatOnce(arg1:string):Promise<string>;

export function ClearChat():Promise<void>;

export function DeleteChatSession(arg1:string):Promise<string>;

export function GetSettings():Promise<Record<string, any>>;

export function GetUsageStats():Promise<Record<string, any>>;

export function ListChatSessions():Promise<chatstore.ProjectBundle>;

export function ListDir(arg1:string):Promise<Array<workspace.Entry>>;

export function ListProjects():Promise<Array<workspace.Project>>;

export function LoadChat(arg1:string):Promise<string>;

export function NewChatSession(arg1:string):Promise<chatstore.Session>;

export function OpenProject(arg1:string):Promise<workspace.Project>;

export function PickProjectDir():Promise<string>;

export function ReadFile(arg1:string):Promise<string>;

export function RunAgent(arg1:string):Promise<void>;

export function RunAgentWithAttachments(arg1:string,arg2:Array<agent.Attachment>):Promise<void>;

export function RunShell(arg1:string):Promise<Record<string, any>>;

export function SSHKeygen(arg1:string):Promise<string>;

export function SSHListKeys():Promise<Array<string>>;

export function SaveChat(arg1:string):Promise<void>;

export function SaveChatSession(arg1:string,arg2:string):Promise<void>;

export function SaveDeepSeekKey(arg1:string):Promise<void>;

export function SaveDeepSeekModel(arg1:string):Promise<void>;

export function SaveGitAuth(arg1:string,arg2:string):Promise<void>;

export function SaveShowFiles(arg1:boolean):Promise<void>;

export function SaveShowTerminal(arg1:boolean):Promise<void>;

export function StartTerminal():Promise<void>;

export function StopAgent():Promise<void>;

export function StopAgentSession(arg1:string):Promise<void>;

export function StopTerminal():Promise<void>;

export function SwitchChatSession(arg1:string):Promise<string>;

export function TerminalWrite(arg1:string):Promise<void>;

export function WriteFile(arg1:string,arg2:string):Promise<void>;
