// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AppInfo() {
  return window['go']['main']['App']['AppInfo']();
}

export function ChatOnce(arg1) {
  return window['go']['main']['App']['ChatOnce'](arg1);
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function ListDir(arg1) {
  return window['go']['main']['App']['ListDir'](arg1);
}

export function ListProjects() {
  return window['go']['main']['App']['ListProjects']();
}

export function OpenProject(arg1) {
  return window['go']['main']['App']['OpenProject'](arg1);
}

export function ReadFile(arg1) {
  return window['go']['main']['App']['ReadFile'](arg1);
}

export function SaveDeepSeekKey(arg1) {
  return window['go']['main']['App']['SaveDeepSeekKey'](arg1);
}

export function SaveDeepSeekModel(arg1) {
  return window['go']['main']['App']['SaveDeepSeekModel'](arg1);
}
